<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MixerDepositCheck" Id="{934eddb0-057b-43a6-a4ff-f563ff1f33e4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK MixerDepositCheck EXTENDS BaseState
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="mIrun" Id="{a0114492-1fc8-4577-86d0-76ddba577705}">
      <Declaration><![CDATA[METHOD mIrun : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF BasePointer^.MachineFlagsAccessI.pStoring THEN
	RETURN;
ELSE
		mNextState();
END_IF]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="MixerDepositCheck">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="MixerDepositCheck.mIrun">
      <LineId Id="3" Count="1" />
      <LineId Id="6" Count="1" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>